### ISSUE TITLE
readme claims to need liboctave-dev on Ubuntu

### ISSUE THREAD

**Issue by cbm755** [gnu-octave/symbolic#1181]
> `sudo apt-get install octave liboctave-dev python-sympy.`

Is that so?  I suspect it only needs `apt install octave`...

**Comment by alexvong1995** [comment]
I think `liboctave-dev` is only needed if we want to use the `mkoctfile` command, which is not the case currently. Pythonic, on the other hand, requires `liboctave-dev` because it uses the `mkoctfile` command.
